// Generated by jextract

package whisper.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct whisper_token_data {
 *     whisper_token id;
 *     whisper_token tid;
 *     float p;
 *     float plog;
 *     float pt;
 *     float ptsum;
 *     int64_t t0;
 *     int64_t t1;
 *     int64_t t_dtw;
 *     float vlen;
 * }
 * }
 */
public class whisper_token_data {

    whisper_token_data() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        whisper_h.C_INT.withName("id"),
        whisper_h.C_INT.withName("tid"),
        whisper_h.C_FLOAT.withName("p"),
        whisper_h.C_FLOAT.withName("plog"),
        whisper_h.C_FLOAT.withName("pt"),
        whisper_h.C_FLOAT.withName("ptsum"),
        whisper_h.C_LONG_LONG.withName("t0"),
        whisper_h.C_LONG_LONG.withName("t1"),
        whisper_h.C_LONG_LONG.withName("t_dtw"),
        whisper_h.C_FLOAT.withName("vlen"),
        MemoryLayout.paddingLayout(4)
    ).withName("whisper_token_data");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * whisper_token id
     * }
     */
    public static final OfInt id$layout() {
        return id$LAYOUT;
    }

    private static final long id$OFFSET = $LAYOUT.byteOffset(groupElement("id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * whisper_token id
     * }
     */
    public static final long id$offset() {
        return id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * whisper_token id
     * }
     */
    public static int id(MemorySegment struct) {
        return struct.get(id$LAYOUT, id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * whisper_token id
     * }
     */
    public static void id(MemorySegment struct, int fieldValue) {
        struct.set(id$LAYOUT, id$OFFSET, fieldValue);
    }

    private static final OfInt tid$LAYOUT = (OfInt)$LAYOUT.select(groupElement("tid"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * whisper_token tid
     * }
     */
    public static final OfInt tid$layout() {
        return tid$LAYOUT;
    }

    private static final long tid$OFFSET = $LAYOUT.byteOffset(groupElement("tid"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * whisper_token tid
     * }
     */
    public static final long tid$offset() {
        return tid$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * whisper_token tid
     * }
     */
    public static int tid(MemorySegment struct) {
        return struct.get(tid$LAYOUT, tid$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * whisper_token tid
     * }
     */
    public static void tid(MemorySegment struct, int fieldValue) {
        struct.set(tid$LAYOUT, tid$OFFSET, fieldValue);
    }

    private static final OfFloat p$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("p"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float p
     * }
     */
    public static final OfFloat p$layout() {
        return p$LAYOUT;
    }

    private static final long p$OFFSET = $LAYOUT.byteOffset(groupElement("p"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float p
     * }
     */
    public static final long p$offset() {
        return p$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float p
     * }
     */
    public static float p(MemorySegment struct) {
        return struct.get(p$LAYOUT, p$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float p
     * }
     */
    public static void p(MemorySegment struct, float fieldValue) {
        struct.set(p$LAYOUT, p$OFFSET, fieldValue);
    }

    private static final OfFloat plog$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("plog"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float plog
     * }
     */
    public static final OfFloat plog$layout() {
        return plog$LAYOUT;
    }

    private static final long plog$OFFSET = $LAYOUT.byteOffset(groupElement("plog"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float plog
     * }
     */
    public static final long plog$offset() {
        return plog$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float plog
     * }
     */
    public static float plog(MemorySegment struct) {
        return struct.get(plog$LAYOUT, plog$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float plog
     * }
     */
    public static void plog(MemorySegment struct, float fieldValue) {
        struct.set(plog$LAYOUT, plog$OFFSET, fieldValue);
    }

    private static final OfFloat pt$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("pt"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float pt
     * }
     */
    public static final OfFloat pt$layout() {
        return pt$LAYOUT;
    }

    private static final long pt$OFFSET = $LAYOUT.byteOffset(groupElement("pt"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float pt
     * }
     */
    public static final long pt$offset() {
        return pt$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float pt
     * }
     */
    public static float pt(MemorySegment struct) {
        return struct.get(pt$LAYOUT, pt$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float pt
     * }
     */
    public static void pt(MemorySegment struct, float fieldValue) {
        struct.set(pt$LAYOUT, pt$OFFSET, fieldValue);
    }

    private static final OfFloat ptsum$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("ptsum"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float ptsum
     * }
     */
    public static final OfFloat ptsum$layout() {
        return ptsum$LAYOUT;
    }

    private static final long ptsum$OFFSET = $LAYOUT.byteOffset(groupElement("ptsum"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float ptsum
     * }
     */
    public static final long ptsum$offset() {
        return ptsum$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float ptsum
     * }
     */
    public static float ptsum(MemorySegment struct) {
        return struct.get(ptsum$LAYOUT, ptsum$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float ptsum
     * }
     */
    public static void ptsum(MemorySegment struct, float fieldValue) {
        struct.set(ptsum$LAYOUT, ptsum$OFFSET, fieldValue);
    }

    private static final OfLong t0$LAYOUT = (OfLong)$LAYOUT.select(groupElement("t0"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t t0
     * }
     */
    public static final OfLong t0$layout() {
        return t0$LAYOUT;
    }

    private static final long t0$OFFSET = $LAYOUT.byteOffset(groupElement("t0"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t t0
     * }
     */
    public static final long t0$offset() {
        return t0$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t t0
     * }
     */
    public static long t0(MemorySegment struct) {
        return struct.get(t0$LAYOUT, t0$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t t0
     * }
     */
    public static void t0(MemorySegment struct, long fieldValue) {
        struct.set(t0$LAYOUT, t0$OFFSET, fieldValue);
    }

    private static final OfLong t1$LAYOUT = (OfLong)$LAYOUT.select(groupElement("t1"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t t1
     * }
     */
    public static final OfLong t1$layout() {
        return t1$LAYOUT;
    }

    private static final long t1$OFFSET = $LAYOUT.byteOffset(groupElement("t1"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t t1
     * }
     */
    public static final long t1$offset() {
        return t1$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t t1
     * }
     */
    public static long t1(MemorySegment struct) {
        return struct.get(t1$LAYOUT, t1$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t t1
     * }
     */
    public static void t1(MemorySegment struct, long fieldValue) {
        struct.set(t1$LAYOUT, t1$OFFSET, fieldValue);
    }

    private static final OfLong t_dtw$LAYOUT = (OfLong)$LAYOUT.select(groupElement("t_dtw"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t t_dtw
     * }
     */
    public static final OfLong t_dtw$layout() {
        return t_dtw$LAYOUT;
    }

    private static final long t_dtw$OFFSET = $LAYOUT.byteOffset(groupElement("t_dtw"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t t_dtw
     * }
     */
    public static final long t_dtw$offset() {
        return t_dtw$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t t_dtw
     * }
     */
    public static long t_dtw(MemorySegment struct) {
        return struct.get(t_dtw$LAYOUT, t_dtw$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t t_dtw
     * }
     */
    public static void t_dtw(MemorySegment struct, long fieldValue) {
        struct.set(t_dtw$LAYOUT, t_dtw$OFFSET, fieldValue);
    }

    private static final OfFloat vlen$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("vlen"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float vlen
     * }
     */
    public static final OfFloat vlen$layout() {
        return vlen$LAYOUT;
    }

    private static final long vlen$OFFSET = $LAYOUT.byteOffset(groupElement("vlen"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float vlen
     * }
     */
    public static final long vlen$offset() {
        return vlen$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float vlen
     * }
     */
    public static float vlen(MemorySegment struct) {
        return struct.get(vlen$LAYOUT, vlen$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float vlen
     * }
     */
    public static void vlen(MemorySegment struct, float fieldValue) {
        struct.set(vlen$LAYOUT, vlen$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

