// Generated by jextract

package whisper.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct whisper_vad_params {
 *     float threshold;
 *     int min_speech_duration_ms;
 *     int min_silence_duration_ms;
 *     float max_speech_duration_s;
 *     int speech_pad_ms;
 *     float samples_overlap;
 * }
 * }
 */
public class whisper_vad_params {

    whisper_vad_params() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        whisper_h.C_FLOAT.withName("threshold"),
        whisper_h.C_INT.withName("min_speech_duration_ms"),
        whisper_h.C_INT.withName("min_silence_duration_ms"),
        whisper_h.C_FLOAT.withName("max_speech_duration_s"),
        whisper_h.C_INT.withName("speech_pad_ms"),
        whisper_h.C_FLOAT.withName("samples_overlap")
    ).withName("whisper_vad_params");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfFloat threshold$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("threshold"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float threshold
     * }
     */
    public static final OfFloat threshold$layout() {
        return threshold$LAYOUT;
    }

    private static final long threshold$OFFSET = $LAYOUT.byteOffset(groupElement("threshold"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float threshold
     * }
     */
    public static final long threshold$offset() {
        return threshold$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float threshold
     * }
     */
    public static float threshold(MemorySegment struct) {
        return struct.get(threshold$LAYOUT, threshold$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float threshold
     * }
     */
    public static void threshold(MemorySegment struct, float fieldValue) {
        struct.set(threshold$LAYOUT, threshold$OFFSET, fieldValue);
    }

    private static final OfInt min_speech_duration_ms$LAYOUT = (OfInt)$LAYOUT.select(groupElement("min_speech_duration_ms"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int min_speech_duration_ms
     * }
     */
    public static final OfInt min_speech_duration_ms$layout() {
        return min_speech_duration_ms$LAYOUT;
    }

    private static final long min_speech_duration_ms$OFFSET = $LAYOUT.byteOffset(groupElement("min_speech_duration_ms"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int min_speech_duration_ms
     * }
     */
    public static final long min_speech_duration_ms$offset() {
        return min_speech_duration_ms$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int min_speech_duration_ms
     * }
     */
    public static int min_speech_duration_ms(MemorySegment struct) {
        return struct.get(min_speech_duration_ms$LAYOUT, min_speech_duration_ms$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int min_speech_duration_ms
     * }
     */
    public static void min_speech_duration_ms(MemorySegment struct, int fieldValue) {
        struct.set(min_speech_duration_ms$LAYOUT, min_speech_duration_ms$OFFSET, fieldValue);
    }

    private static final OfInt min_silence_duration_ms$LAYOUT = (OfInt)$LAYOUT.select(groupElement("min_silence_duration_ms"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int min_silence_duration_ms
     * }
     */
    public static final OfInt min_silence_duration_ms$layout() {
        return min_silence_duration_ms$LAYOUT;
    }

    private static final long min_silence_duration_ms$OFFSET = $LAYOUT.byteOffset(groupElement("min_silence_duration_ms"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int min_silence_duration_ms
     * }
     */
    public static final long min_silence_duration_ms$offset() {
        return min_silence_duration_ms$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int min_silence_duration_ms
     * }
     */
    public static int min_silence_duration_ms(MemorySegment struct) {
        return struct.get(min_silence_duration_ms$LAYOUT, min_silence_duration_ms$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int min_silence_duration_ms
     * }
     */
    public static void min_silence_duration_ms(MemorySegment struct, int fieldValue) {
        struct.set(min_silence_duration_ms$LAYOUT, min_silence_duration_ms$OFFSET, fieldValue);
    }

    private static final OfFloat max_speech_duration_s$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("max_speech_duration_s"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float max_speech_duration_s
     * }
     */
    public static final OfFloat max_speech_duration_s$layout() {
        return max_speech_duration_s$LAYOUT;
    }

    private static final long max_speech_duration_s$OFFSET = $LAYOUT.byteOffset(groupElement("max_speech_duration_s"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float max_speech_duration_s
     * }
     */
    public static final long max_speech_duration_s$offset() {
        return max_speech_duration_s$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float max_speech_duration_s
     * }
     */
    public static float max_speech_duration_s(MemorySegment struct) {
        return struct.get(max_speech_duration_s$LAYOUT, max_speech_duration_s$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float max_speech_duration_s
     * }
     */
    public static void max_speech_duration_s(MemorySegment struct, float fieldValue) {
        struct.set(max_speech_duration_s$LAYOUT, max_speech_duration_s$OFFSET, fieldValue);
    }

    private static final OfInt speech_pad_ms$LAYOUT = (OfInt)$LAYOUT.select(groupElement("speech_pad_ms"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int speech_pad_ms
     * }
     */
    public static final OfInt speech_pad_ms$layout() {
        return speech_pad_ms$LAYOUT;
    }

    private static final long speech_pad_ms$OFFSET = $LAYOUT.byteOffset(groupElement("speech_pad_ms"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int speech_pad_ms
     * }
     */
    public static final long speech_pad_ms$offset() {
        return speech_pad_ms$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int speech_pad_ms
     * }
     */
    public static int speech_pad_ms(MemorySegment struct) {
        return struct.get(speech_pad_ms$LAYOUT, speech_pad_ms$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int speech_pad_ms
     * }
     */
    public static void speech_pad_ms(MemorySegment struct, int fieldValue) {
        struct.set(speech_pad_ms$LAYOUT, speech_pad_ms$OFFSET, fieldValue);
    }

    private static final OfFloat samples_overlap$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("samples_overlap"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float samples_overlap
     * }
     */
    public static final OfFloat samples_overlap$layout() {
        return samples_overlap$LAYOUT;
    }

    private static final long samples_overlap$OFFSET = $LAYOUT.byteOffset(groupElement("samples_overlap"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float samples_overlap
     * }
     */
    public static final long samples_overlap$offset() {
        return samples_overlap$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float samples_overlap
     * }
     */
    public static float samples_overlap(MemorySegment struct) {
        return struct.get(samples_overlap$LAYOUT, samples_overlap$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float samples_overlap
     * }
     */
    public static void samples_overlap(MemorySegment struct, float fieldValue) {
        struct.set(samples_overlap$LAYOUT, samples_overlap$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

