// Generated by jextract

package tensorflow.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TF_AllocatorAttributes {
 *     size_t struct_size;
 *     unsigned char on_host;
 * }
 * }
 */
public class TF_AllocatorAttributes {

    TF_AllocatorAttributes() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        c_api_h.C_LONG.withName("struct_size"),
        c_api_h.C_CHAR.withName("on_host"),
        MemoryLayout.paddingLayout(7)
    ).withName("TF_AllocatorAttributes");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong struct_size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("struct_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t struct_size
     * }
     */
    public static final OfLong struct_size$layout() {
        return struct_size$LAYOUT;
    }

    private static final long struct_size$OFFSET = $LAYOUT.byteOffset(groupElement("struct_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t struct_size
     * }
     */
    public static final long struct_size$offset() {
        return struct_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t struct_size
     * }
     */
    public static long struct_size(MemorySegment struct) {
        return struct.get(struct_size$LAYOUT, struct_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t struct_size
     * }
     */
    public static void struct_size(MemorySegment struct, long fieldValue) {
        struct.set(struct_size$LAYOUT, struct_size$OFFSET, fieldValue);
    }

    private static final OfByte on_host$LAYOUT = (OfByte)$LAYOUT.select(groupElement("on_host"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned char on_host
     * }
     */
    public static final OfByte on_host$layout() {
        return on_host$LAYOUT;
    }

    private static final long on_host$OFFSET = $LAYOUT.byteOffset(groupElement("on_host"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned char on_host
     * }
     */
    public static final long on_host$offset() {
        return on_host$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned char on_host
     * }
     */
    public static byte on_host(MemorySegment struct) {
        return struct.get(on_host$LAYOUT, on_host$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned char on_host
     * }
     */
    public static void on_host(MemorySegment struct, byte fieldValue) {
        struct.set(on_host$LAYOUT, on_host$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

