// Generated by jextract

package tensorflow.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TF_AttrMetadata {
 *     unsigned char is_list;
 *     int64_t list_size;
 *     TF_AttrType type;
 *     int64_t total_size;
 * }
 * }
 */
public class TF_AttrMetadata {

    TF_AttrMetadata() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        c_api_h.C_CHAR.withName("is_list"),
        MemoryLayout.paddingLayout(7),
        c_api_h.C_LONG_LONG.withName("list_size"),
        c_api_h.C_INT.withName("type"),
        MemoryLayout.paddingLayout(4),
        c_api_h.C_LONG_LONG.withName("total_size")
    ).withName("TF_AttrMetadata");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfByte is_list$LAYOUT = (OfByte)$LAYOUT.select(groupElement("is_list"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned char is_list
     * }
     */
    public static final OfByte is_list$layout() {
        return is_list$LAYOUT;
    }

    private static final long is_list$OFFSET = $LAYOUT.byteOffset(groupElement("is_list"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned char is_list
     * }
     */
    public static final long is_list$offset() {
        return is_list$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned char is_list
     * }
     */
    public static byte is_list(MemorySegment struct) {
        return struct.get(is_list$LAYOUT, is_list$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned char is_list
     * }
     */
    public static void is_list(MemorySegment struct, byte fieldValue) {
        struct.set(is_list$LAYOUT, is_list$OFFSET, fieldValue);
    }

    private static final OfLong list_size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("list_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t list_size
     * }
     */
    public static final OfLong list_size$layout() {
        return list_size$LAYOUT;
    }

    private static final long list_size$OFFSET = $LAYOUT.byteOffset(groupElement("list_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t list_size
     * }
     */
    public static final long list_size$offset() {
        return list_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t list_size
     * }
     */
    public static long list_size(MemorySegment struct) {
        return struct.get(list_size$LAYOUT, list_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t list_size
     * }
     */
    public static void list_size(MemorySegment struct, long fieldValue) {
        struct.set(list_size$LAYOUT, list_size$OFFSET, fieldValue);
    }

    private static final OfInt type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TF_AttrType type
     * }
     */
    public static final OfInt type$layout() {
        return type$LAYOUT;
    }

    private static final long type$OFFSET = $LAYOUT.byteOffset(groupElement("type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TF_AttrType type
     * }
     */
    public static final long type$offset() {
        return type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TF_AttrType type
     * }
     */
    public static int type(MemorySegment struct) {
        return struct.get(type$LAYOUT, type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TF_AttrType type
     * }
     */
    public static void type(MemorySegment struct, int fieldValue) {
        struct.set(type$LAYOUT, type$OFFSET, fieldValue);
    }

    private static final OfLong total_size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("total_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t total_size
     * }
     */
    public static final OfLong total_size$layout() {
        return total_size$LAYOUT;
    }

    private static final long total_size$OFFSET = $LAYOUT.byteOffset(groupElement("total_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t total_size
     * }
     */
    public static final long total_size$offset() {
        return total_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t total_size
     * }
     */
    public static long total_size(MemorySegment struct) {
        return struct.get(total_size$LAYOUT, total_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t total_size
     * }
     */
    public static void total_size(MemorySegment struct, long fieldValue) {
        struct.set(total_size$LAYOUT, total_size$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

