// Generated by jextract

package tensorflow.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * union TF_TString_Union {
 *     TF_TString_Large large;
 *     TF_TString_Offset offset;
 *     TF_TString_View view;
 *     TF_TString_Raw raw;
 * }
 * }
 */
public class TF_TString_Union {

    TF_TString_Union() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.unionLayout(
        TF_TString_Large.layout().withName("large"),
        TF_TString_Offset.layout().withName("offset"),
        TF_TString_View.layout().withName("view"),
        TF_TString_Raw.layout().withName("raw")
    ).withName("TF_TString_Union");

    /**
     * The layout of this union
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout large$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("large"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TF_TString_Large large
     * }
     */
    public static final GroupLayout large$layout() {
        return large$LAYOUT;
    }

    private static final long large$OFFSET = $LAYOUT.byteOffset(groupElement("large"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TF_TString_Large large
     * }
     */
    public static final long large$offset() {
        return large$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TF_TString_Large large
     * }
     */
    public static MemorySegment large(MemorySegment union) {
        return union.asSlice(large$OFFSET, large$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TF_TString_Large large
     * }
     */
    public static void large(MemorySegment union, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, union, large$OFFSET, large$LAYOUT.byteSize());
    }

    private static final GroupLayout offset$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TF_TString_Offset offset
     * }
     */
    public static final GroupLayout offset$layout() {
        return offset$LAYOUT;
    }

    private static final long offset$OFFSET = $LAYOUT.byteOffset(groupElement("offset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TF_TString_Offset offset
     * }
     */
    public static final long offset$offset() {
        return offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TF_TString_Offset offset
     * }
     */
    public static MemorySegment offset(MemorySegment union) {
        return union.asSlice(offset$OFFSET, offset$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TF_TString_Offset offset
     * }
     */
    public static void offset(MemorySegment union, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, union, offset$OFFSET, offset$LAYOUT.byteSize());
    }

    private static final GroupLayout view$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("view"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TF_TString_View view
     * }
     */
    public static final GroupLayout view$layout() {
        return view$LAYOUT;
    }

    private static final long view$OFFSET = $LAYOUT.byteOffset(groupElement("view"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TF_TString_View view
     * }
     */
    public static final long view$offset() {
        return view$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TF_TString_View view
     * }
     */
    public static MemorySegment view(MemorySegment union) {
        return union.asSlice(view$OFFSET, view$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TF_TString_View view
     * }
     */
    public static void view(MemorySegment union, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, union, view$OFFSET, view$LAYOUT.byteSize());
    }

    private static final GroupLayout raw$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("raw"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TF_TString_Raw raw
     * }
     */
    public static final GroupLayout raw$layout() {
        return raw$LAYOUT;
    }

    private static final long raw$OFFSET = $LAYOUT.byteOffset(groupElement("raw"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TF_TString_Raw raw
     * }
     */
    public static final long raw$offset() {
        return raw$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TF_TString_Raw raw
     * }
     */
    public static MemorySegment raw(MemorySegment union) {
        return union.asSlice(raw$OFFSET, raw$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TF_TString_Raw raw
     * }
     */
    public static void raw(MemorySegment union, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, union, raw$OFFSET, raw$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this union
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

