// Generated by jextract

package tensorflow.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TF_WhileParams {
 *     const int ninputs;
 *     TF_Graph *const cond_graph;
 *     const TF_Output *const cond_inputs;
 *     TF_Output cond_output;
 *     TF_Graph *const body_graph;
 *     const TF_Output *const body_inputs;
 *     TF_Output *const body_outputs;
 *     const char *name;
 * }
 * }
 */
public class TF_WhileParams {

    TF_WhileParams() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        c_api_h.C_INT.withName("ninputs"),
        MemoryLayout.paddingLayout(4),
        c_api_h.C_POINTER.withName("cond_graph"),
        c_api_h.C_POINTER.withName("cond_inputs"),
        TF_Output.layout().withName("cond_output"),
        c_api_h.C_POINTER.withName("body_graph"),
        c_api_h.C_POINTER.withName("body_inputs"),
        c_api_h.C_POINTER.withName("body_outputs"),
        c_api_h.C_POINTER.withName("name")
    ).withName("TF_WhileParams");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt ninputs$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ninputs"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const int ninputs
     * }
     */
    public static final OfInt ninputs$layout() {
        return ninputs$LAYOUT;
    }

    private static final long ninputs$OFFSET = $LAYOUT.byteOffset(groupElement("ninputs"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const int ninputs
     * }
     */
    public static final long ninputs$offset() {
        return ninputs$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const int ninputs
     * }
     */
    public static int ninputs(MemorySegment struct) {
        return struct.get(ninputs$LAYOUT, ninputs$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const int ninputs
     * }
     */
    public static void ninputs(MemorySegment struct, int fieldValue) {
        struct.set(ninputs$LAYOUT, ninputs$OFFSET, fieldValue);
    }

    private static final AddressLayout cond_graph$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("cond_graph"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TF_Graph *const cond_graph
     * }
     */
    public static final AddressLayout cond_graph$layout() {
        return cond_graph$LAYOUT;
    }

    private static final long cond_graph$OFFSET = $LAYOUT.byteOffset(groupElement("cond_graph"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TF_Graph *const cond_graph
     * }
     */
    public static final long cond_graph$offset() {
        return cond_graph$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TF_Graph *const cond_graph
     * }
     */
    public static MemorySegment cond_graph(MemorySegment struct) {
        return struct.get(cond_graph$LAYOUT, cond_graph$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TF_Graph *const cond_graph
     * }
     */
    public static void cond_graph(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(cond_graph$LAYOUT, cond_graph$OFFSET, fieldValue);
    }

    private static final AddressLayout cond_inputs$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("cond_inputs"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const TF_Output *const cond_inputs
     * }
     */
    public static final AddressLayout cond_inputs$layout() {
        return cond_inputs$LAYOUT;
    }

    private static final long cond_inputs$OFFSET = $LAYOUT.byteOffset(groupElement("cond_inputs"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const TF_Output *const cond_inputs
     * }
     */
    public static final long cond_inputs$offset() {
        return cond_inputs$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const TF_Output *const cond_inputs
     * }
     */
    public static MemorySegment cond_inputs(MemorySegment struct) {
        return struct.get(cond_inputs$LAYOUT, cond_inputs$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const TF_Output *const cond_inputs
     * }
     */
    public static void cond_inputs(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(cond_inputs$LAYOUT, cond_inputs$OFFSET, fieldValue);
    }

    private static final GroupLayout cond_output$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("cond_output"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TF_Output cond_output
     * }
     */
    public static final GroupLayout cond_output$layout() {
        return cond_output$LAYOUT;
    }

    private static final long cond_output$OFFSET = $LAYOUT.byteOffset(groupElement("cond_output"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TF_Output cond_output
     * }
     */
    public static final long cond_output$offset() {
        return cond_output$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TF_Output cond_output
     * }
     */
    public static MemorySegment cond_output(MemorySegment struct) {
        return struct.asSlice(cond_output$OFFSET, cond_output$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TF_Output cond_output
     * }
     */
    public static void cond_output(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, cond_output$OFFSET, cond_output$LAYOUT.byteSize());
    }

    private static final AddressLayout body_graph$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("body_graph"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TF_Graph *const body_graph
     * }
     */
    public static final AddressLayout body_graph$layout() {
        return body_graph$LAYOUT;
    }

    private static final long body_graph$OFFSET = $LAYOUT.byteOffset(groupElement("body_graph"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TF_Graph *const body_graph
     * }
     */
    public static final long body_graph$offset() {
        return body_graph$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TF_Graph *const body_graph
     * }
     */
    public static MemorySegment body_graph(MemorySegment struct) {
        return struct.get(body_graph$LAYOUT, body_graph$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TF_Graph *const body_graph
     * }
     */
    public static void body_graph(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(body_graph$LAYOUT, body_graph$OFFSET, fieldValue);
    }

    private static final AddressLayout body_inputs$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("body_inputs"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const TF_Output *const body_inputs
     * }
     */
    public static final AddressLayout body_inputs$layout() {
        return body_inputs$LAYOUT;
    }

    private static final long body_inputs$OFFSET = $LAYOUT.byteOffset(groupElement("body_inputs"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const TF_Output *const body_inputs
     * }
     */
    public static final long body_inputs$offset() {
        return body_inputs$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const TF_Output *const body_inputs
     * }
     */
    public static MemorySegment body_inputs(MemorySegment struct) {
        return struct.get(body_inputs$LAYOUT, body_inputs$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const TF_Output *const body_inputs
     * }
     */
    public static void body_inputs(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(body_inputs$LAYOUT, body_inputs$OFFSET, fieldValue);
    }

    private static final AddressLayout body_outputs$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("body_outputs"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TF_Output *const body_outputs
     * }
     */
    public static final AddressLayout body_outputs$layout() {
        return body_outputs$LAYOUT;
    }

    private static final long body_outputs$OFFSET = $LAYOUT.byteOffset(groupElement("body_outputs"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TF_Output *const body_outputs
     * }
     */
    public static final long body_outputs$offset() {
        return body_outputs$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TF_Output *const body_outputs
     * }
     */
    public static MemorySegment body_outputs(MemorySegment struct) {
        return struct.get(body_outputs$LAYOUT, body_outputs$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TF_Output *const body_outputs
     * }
     */
    public static void body_outputs(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(body_outputs$LAYOUT, body_outputs$OFFSET, fieldValue);
    }

    private static final AddressLayout name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *name
     * }
     */
    public static final AddressLayout name$layout() {
        return name$LAYOUT;
    }

    private static final long name$OFFSET = $LAYOUT.byteOffset(groupElement("name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *name
     * }
     */
    public static final long name$offset() {
        return name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *name
     * }
     */
    public static MemorySegment name(MemorySegment struct) {
        return struct.get(name$LAYOUT, name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *name
     * }
     */
    public static void name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(name$LAYOUT, name$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

