package com.example.api;

import com.example.service.AnalysisService;
import jakarta.inject.Inject;
import jakarta.ws.rs.*;
import jakarta.ws.rs.core.MediaType;
import java.util.Map;

/**
 * REST resource for AI-generated text detection.
 * <p>
 * This resource provides an endpoint for analyzing text content to determine
 * if it was generated by artificial intelligence. It accepts JSON requests
 * containing text and returns analysis results including detection scores
 * and confidence metrics.
 * </p>
 *
 * @see AnalysisService
 */
@Path("/api/detect")
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
public class DetectionResource {

    /**
     * Service responsible for performing text analysis and AI detection.
     * Injected via CDI.
     */
    @Inject
    AnalysisService service;

    /**
     * Analyzes the provided text to detect AI-generated content.
     * <p>
     * This endpoint accepts a JSON payload containing the text to be analyzed
     * and returns a comprehensive analysis result including detection scores,
     * confidence levels, and other relevant metrics.
     * </p>
     *
     * @param body a map containing the request payload with a "text" key
     *             holding the content to be analyzed. If the "text" key is
     *             not present, an empty string will be analyzed.
     * @return a map containing the analysis results with detection scores,
     *         confidence metrics, and other relevant information about
     *         whether the text appears to be AI-generated
     */
    @POST
    public Map<String, Object> detect(Map<String, String> body) {
        String text = body.getOrDefault("text", "");
        return service.analyze(text);
    }
}